import os
from flask import Flask, request, jsonify
from pipeline import reflection_loop
from format_engine import FormatEngine

app = Flask(__name__)
format_engine = FormatEngine()

@app.route("/", methods=["GET"])
def health_check():
    return "AI Influencer Intelligence Platform is running.", 200

@app.route("/trigger", methods=["POST"])
def trigger_pipeline():
    """
    Triggers the analysis pipeline.
    Expects JSON payload with 'data' key.
    Optional 'format' key: 'html' (default) or 'markdown'.
    """
    try:
        req_data = request.get_json(silent=True)
        if not req_data or 'data' not in req_data:
            return jsonify({"error": "Missing 'data' in request body"}), 400

        input_data = req_data['data']
        output_format = req_data.get('format', 'html').lower()

        # Run the pipeline
        result = reflection_loop(input_data)

        if "error" in result:
             return jsonify(result), 500

        # Format the output
        final_content = result.get("final_content", "")

        # Prepare data for formatting
        render_data = {
            "title": "AI Influencer Analysis",
            "content": final_content,
            "summary": "Analysis generated by Claude 3.5 Haiku and refined by Gemini 1.5 Flash."
        }

        if output_format == 'markdown':
            formatted_output = format_engine.render_markdown(render_data)
            return formatted_output, 200, {'Content-Type': 'text/markdown'}
        else:
            # Simple HTML template
            html_template = """
            <!DOCTYPE html>
            <html>
            <head>
                <title>{{ title }}</title>
                <style>
                    body { font-family: sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 20px; }
                    h1 { color: #333; }
                    .summary { background: #f4f4f4; padding: 10px; border-radius: 5px; margin-bottom: 20px; }
                    .content { white-space: pre-wrap; }
                </style>
            </head>
            <body>
                <h1>{{ title }}</h1>
                <div class="summary">
                    <p><strong>Summary:</strong> {{ summary }}</p>
                </div>
                <div class="content">{{ content }}</div>
            </body>
            </html>
            """
            # Note: In a real app, content might be HTML safe or need markdown-to-html conversion.
            # For now, we assume text content. Added white-space: pre-wrap to preserve newlines.
            formatted_output = format_engine.render_html(render_data, html_template)
            return formatted_output, 200, {'Content-Type': 'text/html'}

    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    # Cloud Run expects the app to listen on the port defined by the PORT environment variable.
    port = int(os.environ.get("PORT", 8080))
    app.run(host="0.0.0.0", port=port)
